feat: allow installing multiple extensions at once

diff --git a/install-wolfi-php-extensions b/install-wolfi-php-extensions
--- a/install-wolfi-php-extensions
+++ b/install-wolfi-php-extensions
@@ -18,62 +18,75 @@ case $(uname -m) in
         ;;
 esac
 
+if [ ! -e /usr/lib/php/modules/ ]; then
+    mkdir -p /usr/lib/php/modules/
+fi
+
 if ! which curl 1> /dev/null 2> /dev/null; then
     apk add --no-cache curl
 fi
 
-case "$@" in 
-    blackfire)
-        if [ -e "$phpConfDir/blackfire.ini" ]; then
-            echo "blackfire already installed, skipping";
-        else
-            before=$(pwd)
-            tmpDir=$(mktemp -d)
-            cd "$tmpDir"
-            curl -sSLf --user-agent Docker "https://blackfire.io/api/v1/releases/probe/php/linux/$arch/$phpVersion" | tar xz
-            mv $tmpDir/blackfire*.so "$phpModuleDir/blackfire.so"
-    
-            echo "extension=blackfire.so" > "$phpConfDir/blackfire.ini"
-            echo "blackfire.agent_socket=tcp://blackfire:8307" >> "$phpConfDir/blackfire.ini"
-            cd "$before"
-            rm -rf "$tmpDir"
-            echo "Installed blackfire"
-        fi
-        ;;
-    tideways)
-        if [ -e "$phpConfDir/tideways.ini" ]; then
-                echo "tideways already installed, skipping";
-        else
-            before=$(pwd)
-            tidewaysArch=$arch
+while :; do
+    if test $# -lt 1; then
+        break
+    fi
 
-            if [ $tidewaysArch == "amd64" ]; then
-                tidewaysArch="x86_64"
+    case $1 in 
+        blackfire)
+            if [ -e "$phpConfDir/blackfire.ini" ]; then
+                echo "blackfire already installed, skipping";
+            else
+                before=$(pwd)
+                tmpDir=$(mktemp -d)
+                cd "$tmpDir"
+                curl -sSLf --user-agent Docker "https://blackfire.io/api/v1/releases/probe/php/linux/$arch/$phpVersion" | tar xz
+                mv blackfire*.so "$phpModuleDir/blackfire.so"
+        
+                echo "extension=blackfire.so" > "$phpConfDir/blackfire.ini"
+                echo "blackfire.agent_socket=tcp://blackfire:8307" >> "$phpConfDir/blackfire.ini"
+                cd "$before"
+                rm -rf "$tmpDir"
+                echo "Installed blackfire"
             fi
+            ;;
+        tideways)
+            if [ -e "$phpConfDir/tideways.ini" ]; then
+                    echo "tideways already installed, skipping";
+            else
+                before=$(pwd)
+                tidewaysArch=$arch
 
-            url=$(curl -sSLf -o - https://tideways.com/profiler/downloads | grep -Eo "\"[^\"]+/tideways-php-([0-9]+\.[0-9]+\.[0-9]+)-$tidewaysArch.tar.gz\"" | cut -d'"' -f2)
-            
-            if [ $url == "" ]; then
-                echo "Could not gather download link from Tideways. Please open a Issue"
-                exit 1
+                if [ $tidewaysArch == "amd64" ]; then
+                    tidewaysArch="x86_64"
+                fi
+
+                url=$(curl -sSLf -o - https://tideways.com/profiler/downloads | grep -Eo "\"[^\"]+/tideways-php-([0-9]+\.[0-9]+\.[0-9]+)-$tidewaysArch.tar.gz\"" | cut -d'"' -f2)
+                
+                if [ $url == "" ]; then
+                    echo "Could not gather download link from Tideways. Please open a Issue"
+                    exit 1
+                fi
+
+                tmpDir=$(mktemp -d)
+                cd "$tmpDir"
+
+                curl -sSLf --user-agent Docker $url | tar xz
+
+                cd tideways*
+
+                mv "tideways-php-$phpVersionDot.so" "$phpModuleDir/tideways.so"
+                echo "extension=tideways.so" > "$phpConfDir/tideways.ini"
+
+                cd "$before"
+                rm -rf "$tmpDir"
+                echo "Installed tideways"
             fi
+            ;;
+        *)
+            echo "Is unsupported right now. feel free to make a Issue"
+            ;;
+    esac
 
-            tmpDir=$(mktemp -d)
-            cd "$tmpDir"
+    shift
 
-            curl -sSLf --user-agent Docker $url | tar xz
-
-            cd tideways*
-
-            mv "tideways-php-$phpVersionDot.so" "$phpModuleDir/tideways.so"
-            echo "extension=tideways.so" > "$phpConfDir/tideways.ini"
-
-            cd "$before"
-            rm -rf "$tmpDir"
-            echo "Installed tideways"
-        fi
-        ;;
-    *)
-        echo "Is unsupported right now. feel free to make a Issue"
-        ;;
-esac
+done
